In [2]:
import csv

%precision 2

'%.2f'

In [4]:
with open("mpg.csv") as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [6]:
mpg[0]

OrderedDict([('', '1'),
             ('manufacturer', 'audi'),
             ('model', 'a4'),
             ('displ', '1.8'),
             ('year', '1999'),
             ('cyl', '4'),
             ('trans', 'auto(l5)'),
             ('drv', 'f'),
             ('cty', '18'),
             ('hwy', '29'),
             ('fl', 'p'),
             ('class', 'compact')])

In [7]:
mpg[-1]

OrderedDict([('', '234'),
             ('manufacturer', 'volkswagen'),
             ('model', 'passat'),
             ('displ', '3.6'),
             ('year', '2008'),
             ('cyl', '6'),
             ('trans', 'auto(s6)'),
             ('drv', 'f'),
             ('cty', '17'),
             ('hwy', '26'),
             ('fl', 'p'),
             ('class', 'midsize')])

In [8]:
mpg[0:4]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [9]:
len(mpg)

234

In [11]:
mpg[0]["model"]

'a4'

In [17]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [16]:
for x in mpg[0].keys():
    print(x)


manufacturer
model
displ
year
cyl
trans
drv
cty
hwy
fl
class


In [24]:
x = [float(d['cty']) for d in mpg]
print(sum(x))
print(sum(x)/len(mpg))

3945.0
16.858974358974358


In [25]:
sum(float(d['cty']) for d in mpg)/len(mpg)

16.86

In [26]:
sum(float(d['hwy']) for d in mpg)/len(mpg)

23.44

In [31]:
cylinders = set([d['cyl'] for d in mpg])
cylinders

{'4', '5', '6', '8'}

In [32]:
CtyMpgByCyl = []

for c in cylinders:
    summpg = 0
    cyltypecount =0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg/cyltypecount))
CtyMpgByCyl.sort(key=lambda x: x[0])

In [33]:
print(CtyMpgByCyl)

[('4', 21.012345679012345), ('5', 20.5), ('6', 16.21518987341772), ('8', 12.571428571428571)]


In [35]:
mpg[0]['class']

'compact'

In [36]:
vehicleclass = set([d['class'] for d in mpg])

In [37]:
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [43]:
HwyMpgByClass = []

for t in vehicleclass:
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class'] == t:
            summpg += float(d['hwy'])
            vclasscount += 1
    HwyMpgByClass.append((t, summpg/vclasscount))
HwyMpgByClass.sort(key=lambda x: x[1])

In [44]:
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

<H1> Dates and Times

import datetime as dt
import time as tm

In [46]:
tm.time()

1520713743.67

In [49]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 3, 10, 12, 29, 41, 919749)

In [53]:
print(dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second, dtnow.microsecond)

2018 3 10 12 29 41 919749


In [55]:
delta = dt.timedelta(days = 100)

In [56]:
delta

datetime.timedelta(100)

In [57]:
today = dt.date.today()

In [58]:
today

datetime.date(2018, 3, 10)

In [59]:
today - delta

datetime.date(2017, 11, 30)

In [60]:
today > today-delta

True

<H1> Objects and map()

In [61]:
class Person:
    department = "School of Information"
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [62]:
P = Person()

In [63]:
P.department

'School of Information'

In [64]:
P.set_name("John Goodman")

In [65]:
P.set_location("Santa Clara")

In [66]:
P.name

'John Goodman'

In [67]:
P.location

'Santa Clara'

<H1> map()

In [74]:
store1 = [11.0, 12.4, 9.45, 3.2]
store2 = [11.4, 10.9, 8.5, 32.0]
lowest = map(min, store1, store2)
lowest

In [75]:
for x in lowest:
    print(x)

11.0
10.9
8.5
3.2


In [79]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    x = person.split(' ')
    return('{} {}'.format(x[0], x[-1]))

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

<H1> Lambda Funcs

In [81]:
lammy = lambda a, b, c: a*b+c

In [257]:
type(lammy)

function

In [258]:
type(lambda x: x+1)

function

In [84]:
lammy(3,3,3)

12

In [125]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

#option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

#option 2
list(map(split_title_and_name, people)) == list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

True
True
True
True


True

In [123]:
for person in people:
    print((lambda x: x.split()[0] + ' ' + x.split()[-1])(person))

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero


<H1> List comprehension

In [128]:
evennum = [num for num in range(0,20) if num %2 == 0]

In [129]:
evennum

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [132]:
l = []
for num in range(0,20):
    if num %2 ==0:
        l.append(num)

In [133]:
l

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [138]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(10)]

True

In [140]:
lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'

answer = [a+b+c+d for a in lowercase for b in lowercase for c in digits for d in digits]

In [141]:
answer[:10]

['aa00',
 'aa01',
 'aa02',
 'aa03',
 'aa04',
 'aa05',
 'aa06',
 'aa07',
 'aa08',
 'aa09']

In [142]:
len(answer)

67600

In [143]:
answer[67590:]

['zz90',
 'zz91',
 'zz92',
 'zz93',
 'zz94',
 'zz95',
 'zz96',
 'zz97',
 'zz98',
 'zz99']

In [144]:
import numpy as np

In [145]:
x = np.array([1,2,3,4])

In [146]:
y = np.array([5,6,7,8])

In [151]:
z = np.stack((x, y))
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [154]:
w = np.array([[1,2,3],[4,5,6],[7,8,9]])
w

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [158]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [159]:
n.reshape(5,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [168]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [169]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [170]:
o.reshape(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [172]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [173]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [174]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
np.diag(y)

array([[5, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

In [177]:
np.array([1,4,5]*3)

array([1, 4, 5, 1, 4, 5, 1, 4, 5])

In [178]:
np.repeat([1,4,5],3)

array([1, 1, 1, 4, 4, 4, 5, 5, 5])

In [180]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [181]:
q = np.zeros([2,3])

In [183]:
np.vstack((p, q))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [184]:
np.vstack((p,p*2))

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [185]:
print(x, y)

[1 2 3 4] [5 6 7 8]


In [186]:
x + y

array([ 6,  8, 10, 12])

In [187]:
x*y

array([ 5, 12, 21, 32])

In [188]:
x.dot(y)

70

In [190]:
v = np.array([y, y**2])
v

array([[ 5,  6,  7,  8],
       [25, 36, 49, 64]])

In [191]:
v.shape

(2, 4)

In [193]:
v.T.shape

(4, 2)

In [194]:
v

array([[ 5,  6,  7,  8],
       [25, 36, 49, 64]])

In [195]:
v.T

array([[ 5, 25],
       [ 6, 36],
       [ 7, 49],
       [ 8, 64]])

In [196]:
v.dtype

dtype('int64')

In [197]:
v.astype('f')

array([[ 5.,  6.,  7.,  8.],
       [25., 36., 49., 64.]], dtype=float32)

In [198]:
a = np.array([-4,-2,1,3,5])

In [199]:
a.sum()

3

In [200]:
print(a.max(), a.min())


5 -4


In [201]:
print(a.mean(), a.std())

0.6 3.2619012860600183


In [202]:
print(a.argmax(), a.argmin())

4 0


In [204]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [205]:
s[0], s[5], s[6:13]

(0, 25, array([ 36,  49,  64,  81, 100, 121, 144]))

In [207]:
s[-4:]

array([ 81, 100, 121, 144])

In [208]:
s[-1]

144

In [211]:
s[-5::-2], a[-5::2]

(array([64, 36, 16,  4,  0]), array([-4,  1,  5]))

In [214]:
t = np.arange(36)
t = t.reshape(6,6)
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [217]:
t[2,2], t[3:,:4]

(14, array([[18, 19, 20, 21],
        [24, 25, 26, 27],
        [30, 31, 32, 33]]))

In [220]:
u = t.copy()
u

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [221]:
u[:3,:4] = 0

In [225]:
u

array([[ 0,  0,  0,  0,  4,  5],
       [ 0,  0,  0,  0, 10, 11],
       [ 0,  0,  0,  0, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [226]:
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [227]:
t[-1,::2]

array([30, 32, 34])

In [229]:
t[t>20].reshape(3,5)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [231]:
t[t>25] = 25
t

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [234]:
t2 = t[:3,:3]
t2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [235]:
t2[:] = 0

In [236]:
t2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [237]:
t

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [238]:
t2 = t.copy()
t2

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [239]:
t2[:] = 10

In [240]:
t2

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [241]:
t

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [242]:
test = np.random.randint(0,10, (4,3))
test

array([[0, 8, 9],
       [0, 4, 8],
       [4, 8, 4],
       [5, 7, 7]])

In [243]:
for row in test:
    print(row)

[0 8 9]
[0 4 8]
[4 8 4]
[5 7 7]


In [244]:
for i in range(len(test)):
    print(test[i])

[0 8 9]
[0 4 8]
[4 8 4]
[5 7 7]


In [252]:
for i, row in enumerate(test):
    print("row", i, "is: ", row)

row 0 is:  [0 8 9]
row 1 is:  [0 4 8]
row 2 is:  [4 8 4]
row 3 is:  [5 7 7]


In [253]:
test2 = test**2
test2

array([[ 0, 64, 81],
       [ 0, 16, 64],
       [16, 64, 16],
       [25, 49, 49]])

In [255]:
for i, j in zip(test, test2):
    print(i, '*', j, '=', i*j)

[0 8 9] * [ 0 64 81] = [  0 512 729]
[0 4 8] * [ 0 16 64] = [  0  64 512]
[4 8 4] * [16 64 16] = [ 64 512  64]
[5 7 7] * [25 49 49] = [125 343 343]


In [256]:
['a','b','c'] + [1,2,3]

['a', 'b', 'c', 1, 2, 3]

In [259]:
foo = np.arange(36)

In [261]:
foo = foo.reshape(6,6)

In [262]:
foo

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [270]:
foo.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [272]:
foo[2:4,2:4]

array([[14, 15],
       [20, 21]])